# Generated by Django 3.2.9 on 2021-11-25 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ejemplar', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prestamo',
            old_name='localizacion',
            new_name='fechad',
        ),
        migrations.RenameField(
            model_name='prestamo',
            old_name='codigo',
            new_name='fechap',
        ),
    ]
