# Generated by Django 3.2.9 on 2021-11-25 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ejemplar', '0002_auto_20211125_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='fechad',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='fechap',
            field=models.DateField(),
        ),
    ]
